# Values in here are hard-coded in such a way to enable use in conjunction
# with ./docker/compose.yml.  Update accordingly and locally.
command_endpoint = "tcp://coordinator:16999"
# Addresses can be dictionaries consisting of the bind and connect address: the
# bind address is the local address that the coordinator will bind it's end of
# the pipeline to. connect is the endpoint that will be passed to remote
# workers for them to connect to deliver done jobs and logs. These two are
# separate to work around NAT. Making the address a string makes both values
# equal in the validation phase of config parsing
#	{ bind = "tcp://127.0.0.1:16001", connect = "tcp://localhost:16001" }
intake = "tcp://coordinator:16998"
worker_endpoint = "tcp://coordinator:16001"
# Under this path projects and their builds reside as <project>/<build_ts>, as
# well as a few special directories:
#  - ./{_coldir,_tmp}:
#        for storage of temporary files and artifact collection
#  - ./<project>/rolling:
#        rolling artifact repositories. These always contain the most
#        up-to-date versions of a given artifact, and are used as seeds of
#        incremental builds.
#  - ./<project>/distrib:
#        The distribution repository for a given project. Used in comparisons
#        in the web packages display. This directory is only ever read, and
#        hence is not subject to the same-filesystem recommendation.
#  - ./<project>/mirror_build:
#        The directory in which xbstrap-mirror is executed. Intended to be
#        exposed on the same path as specified in the mirror_root variables.
#  - ./<project>/current:
#        A link to the currently running build.
# It is advisable to keep all of the above (especially the collection and
# temporary directory) on one filesystem, to allow for fast atomic moves,
# unless stated otherwise.
project_base = "/projects"
# do not change this value after initial setup, it's used by the workers to
# determine the path where packages should be built, because some packages
# decided hard coding absolute paths wasn't a terrible idea somehow
build_root = "/worker"
# Store artifact history in PostgreSQL, for statistical purposes.
# See https://www.postgresql.org/docs/current/libpq-envars.html for specifying
# connection parameters.
artifact_history = true

[projects.managarm]
git = "https://github.com/managarm/bootstrap-managarm.git"
description = "Pragmatic microkernel-based OS with fully asynchronous I/O"
classes = ["managarm"]
# external access to tools and packages repo, to be used by worker (through
# xbps-install and just a simple tarfile download)
packages = "/projects/managarm/current/package_repo"
tools = "/projects/managarm/current/tool_repo"
fingerprint = "@FINGERPRINT@"
incremental = true
distfile_path = "xbbs/x86_64/"
#mirror_root = "http://localhost/"

[projects.managarm_aarch64]
git = "https://github.com/managarm/bootstrap-managarm.git"
description = "Pragmatic microkernel-based OS with fully asynchronous I/O. Now on an ARM near you!"
classes = ["managarm"]
# external access to tools and packages repo, to be used by worker (through
# xbps-install and just a simple tarfile download)
packages = "/projects/managarm_aarch64/current/package_repo"
tools = "/projects/managarm_aarch64/current/tool_repo"
fingerprint = "@FINGERPRINT@"
incremental = true
distfile_path = "xbbs/aarch64"
