# Convenience compose to do local build bringup.  Removes all system
# inconsistencies, at long last!
#
# Also this is far less ugly.

name: xbbs-dev

services:
  coordinator:
    init: true
    image: xbbs-devrt
    pull_policy: never
    build:
      context: ../
      dockerfile: docker/Dockerfile-devrt
    ports:
      - 10999:10999/tcp
    volumes:
      - src:/src
      - work:/work
      - mirrors:/mirrors
      - ../config-examples/coordinator.toml:/etc/xbbs/coordinator.toml.in:ro
    environment:
      XBBS_CMD: |2
        set -xe
        (
          cd /work/
          mkdir -p keys
          cd keys
          set -- *
          if [ "$$1" = '*' ]; then
            /src/xbps-keygen 'xbbs tester'
            fingerprint="$(echo *.rsa | sed s/\\.rsa//)"
          elif [ "$$#" -eq 2 ]; then
            fingerprint="$${1%.*}"
          else
            printf 'what?  two keys?'
            exit 1
          fi
          sed "s/@FINGERPRINT@/$$fingerprint/g" /etc/xbbs/coordinator.toml.in \
            >/etc/xbbs/coordinator.toml
        )
        exec xbbs-coordinator

  worker:
    init: true
    image: xbbs-devrt
    pull_policy: never
    build:
      context: ../
      dockerfile: docker/Dockerfile-devrt
    volumes:
      - src:/src
      - ../config-examples/worker.toml:/etc/xbbs/worker.toml:ro
      - work:/work
    environment:
      XBBS_CMD: set -xe; mkdir -p /work; exec xbbs-worker
    # TODO(arsen): will need to make this less aggressive before utilizing
    # docker in prod
    privileged: true

  web:
    image: xbbs-devrt
    pull_policy: never
    ports:
      - 8000:5000/tcp
    build:
      context: ../
      dockerfile: docker/Dockerfile-devrt
    volumes:
      - work:/work
    environment:
      XBBS_CMD: FLASK_APP=xbbs.web.wsgi FLASK_ENV=development XBBS_COORDINATOR_URL=http://coordinator:10999/ XBBS_COORDINATOR_WORK_ROOT=/work/ exec flask run --debug -h 0.0.0.0

  mirror_server:
    build:
      context: .
      dockerfile: Dockerfile-mirror-server
    volumes:
      - mirrors:/mirrors
      - ./mirrors-httpd.conf:/usr/local/apache2/conf/httpd.conf:ro

volumes:
  src:
    driver: local
    driver_opts:
      type: overlay
      o: lowerdir=${PWD}/..,upperdir=${PWD}/src-ov-upper,workdir=${PWD}/src-ov-work
      device: overlay
  work:
  mirrors:
