FROM debian:latest

RUN apt-get update
RUN apt-get -y install  \
    --no-install-recommends \
    wget \
    git \
    mercurial \
    subversion \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    libpq-dev \
    python3-all-dev

RUN mkdir /src
RUN python3 -m venv /venv

# Files from the sources toplevel needed to do the initial editable install
# into a virtualenv.
ADD pyproject.toml \
    xbps-keygen \
    README.rst \
    /src
# Separate step because Docker copies contents
ADD xbbs /src/xbbs

# bootstrap-managarm uses y4
RUN . /venv/bin/activate \
    && pip install y4
RUN . /venv/bin/activate && pip install -e /src/.'[history]'

# Download cbuildrt v0.1.3
RUN cd /usr/local/bin \
    && ( wget -O- https://github.com/managarm/cbuildrt/releases/download/v0.1.3/cbuildrt-linux-x86_64-static.tar \
    | tar -xf - )

# Download the build environment
RUN mkdir -p /var/lib/cbuildrt/managarm-buildenv \
    && cd /var/lib/cbuildrt/managarm-buildenv \
    && ( wget -O- https://repos.managarm.org/buildenv/managarm-buildenv.tar.gz \
    | tar -xzf - --strip-components=1 -p )

# Download and install xbps (same version as xbstrap does)
RUN cd /usr/local/bin \
    &&  ( wget -O- https://repo-default.voidlinux.org/static/xbps-static-static-0.59_5.x86_64-musl.tar.xz \
    | tar -xJf - ./usr/bin/ --strip-components=3 )

COPY --chmod=755 <<"EOF" /run_xbbs.sh
#!/bin/sh
set -e
. /venv/bin/activate
eval "${XBBS_CMD?need XBBS_CMD set}"
EOF

CMD ["/run_xbbs.sh"]

# Local Variables:
# mode: dockerfile
# End:
