user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        listen 0.0.0.0:80;
        listen [::]:80;

        location / {
            proxy_redirect          http:// https://;
            proxy_pass              http://web:5000/;
        }

        location /int_coord_root/ {
            internal;
            alias /work/;
        }
    }
}
